server:
  port: 80
  bind: 0.0.0.0
  log: 'WebhookEventServer.log'
  secret: 'top_secret'
  # GitHub API request info
  token_file: 'token.pat'
  github_api: 'https://api.github.com'
  owner: jefeish
  organization: jchallenge1

# list the Webhook events to respond to
webhooks:
  # events list from - https://developer.github.com/webhooks/
  - event: issues
    description: 'Webhook event, issue opened'
    # the payload_attr acts as a filter option
    payload_attrs:
      - action: opened
    actions:
      - notification

  - event: repository
    description: 'create an issue when a repository gets deleted'
    payload_attrs:
      - action: deleted
    actions:
      - create_issue

  - event: issues
    description: ''
    payload_attrs:
      - action: closed
    actions:
